modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="macgamer"
version="1.0.0"
displayName="MacGAMER"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="henrynieves, MCreator"

[[dependencies.macgamer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



